/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vechicle.parking.mysql;

import java.awt.event.*;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author azfar
 */
public class ParkingMenu extends javax.swing.JFrame {

    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form ParkingMenu
     */
    public ParkingMenu() {
        conn = javaconnect.ConnecrDb();
        initComponents();
        showingParkingStatus();
        showingCheckingStatus();
        showDate();
        showTime();
        AnotherShowTime();
        ParkingCheck();
        
    }
    
    void ParkingCheck(){
         
        try{
               
            String sql = "select * from Parking";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if(rs.next()){
                
                    String add1 = rs.getString("parking_01");
                    parkingOne.setText(add1);

                    String add2 = rs.getString("parking_02");
                    parkingTwo.setText(add2);
                    
                    String add3 = rs.getString("parking_03");
                    parkingThree.setText(add3);

                    String add4 = rs.getString("parking_04");
                    parkingFour.setText(add4);
                    
                    String add5 = rs.getString("parking_05");
                    parkingFive.setText(add5);

                    String add6 = rs.getString("parking_06");
                    parkingSix.setText(add6);
                    
                    String add7 = rs.getString("parking_07");
                    parkingSeven.setText(add7);

                    String add8 = rs.getString("parking_08");
                    parkingEight.setText(add8);
                    
                    String add9 = rs.getString("parking_09");
                    parkingNine.setText(add9);

                    String add10 = rs.getString("parking_10");
                    parkingTen.setText(add10);

                }

            }catch(Exception e){

            }
    }
    
    void ClearAll(){
        status_vehicle_ID.setText("");
        status_vehicle_type.setText("");
        status_vehicle_token_no.setText("");
        status_vehicle_parking_no.setText("");
        status_vehicle_driver.setText("");
        status_vehicle_entrance_date.setText("");
        status_vehicle_entrance_time.setText("");
    }
    void showDate(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        datetab.setText(s.format(d));
        vehicle_entrance_date.setText(s.format(d));
    }
    
    void showTime(){
        new Timer(0, new ActionListener(){
            
            public void actionPerformed(ActionEvent e){
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                timetab.setText(s.format(d));
                
            }
        }).start();
    }
    
    void AnotherShowTime(){
        new Timer(0, new ActionListener(){
            
            public void actionPerformed(ActionEvent e){
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm");
                vehicle_entrance_time.setText(s.format(d));
                
            }
        }).start();
    }
    
    
    private void showingParkingStatus(){
        
        try{
            String sql = "select * from Vehicle_Parking_Details";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            parking_status_table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    
    private void showingCheckingStatus(){
        
        try{
            String sql = "select * from Vehicle_Check_In_Out";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            check_InOut_table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vehicle_TypeSeletion_group = new javax.swing.ButtonGroup();
        gender_Seletion_group = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        parking_status_table = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        status_vehicle_ID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        status_vehicle_parking_no = new javax.swing.JTextField();
        status_vehicle_token_no = new javax.swing.JTextField();
        status_vehicle_type = new javax.swing.JTextField();
        status_vehicle_driver = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        vehicle_search = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        status_vehicle_entrance_date = new javax.swing.JTextField();
        status_vehicle_entrance_time = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        clear_all = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        check_InOut_table = new javax.swing.JTable();
        check_In_Out_Search = new javax.swing.JTextField();
        show_all = new javax.swing.JButton();
        search_Selection = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        vehicle_ID = new javax.swing.JTextField();
        vehicle_token_no = new javax.swing.JTextField();
        vehicle_parking_no = new javax.swing.JTextField();
        vehicle_entrance_time = new javax.swing.JTextField();
        vehicle_entrance_date = new javax.swing.JTextField();
        car_radioButton = new javax.swing.JRadioButton();
        bike_radioButton = new javax.swing.JRadioButton();
        male_radioButton = new javax.swing.JRadioButton();
        female_radioButton = new javax.swing.JRadioButton();
        add_parking = new javax.swing.JButton();
        parking_clear_all = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        parkingOne = new javax.swing.JTextField();
        parkingTwo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        parkingThree = new javax.swing.JTextField();
        parkingFour = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        parkingFive = new javax.swing.JTextField();
        parkingSix = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        parkingSeven = new javax.swing.JTextField();
        parkingEight = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        parkingNine = new javax.swing.JTextField();
        parkingTen = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        datetab = new javax.swing.JTextField();
        timetab = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 0));

        jTabbedPane1.setBackground(new java.awt.Color(153, 153, 153));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        parking_status_table.setBackground(new java.awt.Color(102, 255, 255));
        parking_status_table.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        parking_status_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        parking_status_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parking_status_tableMouseClicked(evt);
            }
        });
        parking_status_table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                parking_status_tableKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                parking_status_tableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(parking_status_table);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Vehicle ID :");

        status_vehicle_ID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Vehicle Type :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Token NO :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Parking No : ");

        status_vehicle_parking_no.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        status_vehicle_token_no.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        status_vehicle_type.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        status_vehicle_driver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Driver : ");

        vehicle_search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vehicle_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vehicle_searchKeyReleased(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setText("Search by Vehicle (ID/Token) : ");

        jButton1.setText("Exit Parking");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        status_vehicle_entrance_date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        status_vehicle_entrance_time.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Entrance Time : ");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Entrance Date : ");

        clear_all.setText("Clear All");
        clear_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_allActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(56, 56, 56))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(36, 36, 36)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(56, 56, 56)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(44, 44, 44)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(84, 84, 84)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(status_vehicle_driver, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(status_vehicle_parking_no, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(status_vehicle_token_no, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(status_vehicle_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(status_vehicle_type, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(vehicle_search, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(status_vehicle_entrance_date, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(status_vehicle_entrance_time, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(clear_all, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(vehicle_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(status_vehicle_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(status_vehicle_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(status_vehicle_token_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(status_vehicle_parking_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(status_vehicle_driver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(status_vehicle_entrance_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(status_vehicle_entrance_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear_all, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("  Parking Status  ", jPanel2);

        check_InOut_table.setBackground(new java.awt.Color(51, 255, 204));
        check_InOut_table.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        check_InOut_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(check_InOut_table);

        check_In_Out_Search.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        check_In_Out_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                check_In_Out_SearchKeyReleased(evt);
            }
        });

        show_all.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        show_all.setText("Show All");
        show_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_allActionPerformed(evt);
            }
        });

        search_Selection.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        search_Selection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Item", "Vehicle_ID", "Vehicle_Type", "Token_No", "Parking" }));
        search_Selection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_SelectionActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel31.setText("Search : ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(check_In_Out_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(search_Selection, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(show_all))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_In_Out_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_Selection, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show_all, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("  Check In/Out  ", jPanel3);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Vehicle ID :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Vehicle Type :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Token NO :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Parking No : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Driver : ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Time : ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Date : ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Entrance : ");

        vehicle_ID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        vehicle_token_no.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        vehicle_parking_no.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vehicle_parking_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vehicle_parking_noKeyReleased(evt);
            }
        });

        vehicle_entrance_time.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        vehicle_entrance_date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        vehicle_TypeSeletion_group.add(car_radioButton);
        car_radioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        car_radioButton.setText("Car");
        car_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                car_radioButtonActionPerformed(evt);
            }
        });

        vehicle_TypeSeletion_group.add(bike_radioButton);
        bike_radioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bike_radioButton.setText("Motor Bike");
        bike_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bike_radioButtonActionPerformed(evt);
            }
        });

        gender_Seletion_group.add(male_radioButton);
        male_radioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        male_radioButton.setText("Male");
        male_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                male_radioButtonActionPerformed(evt);
            }
        });

        gender_Seletion_group.add(female_radioButton);
        female_radioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        female_radioButton.setText("Female");
        female_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_radioButtonActionPerformed(evt);
            }
        });

        add_parking.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add_parking.setText("Add");
        add_parking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_parkingActionPerformed(evt);
            }
        });

        parking_clear_all.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        parking_clear_all.setText("Clear All");
        parking_clear_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parking_clear_allActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Parking Detail :");

        parkingOne.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        parkingTwo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Parking 01: ");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Parking 02: ");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Parking 03: ");

        parkingThree.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        parkingFour.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Parking 04: ");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("Parking 05: ");

        parkingFive.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        parkingSix.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("Parking 06: ");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setText("Parking 07: ");

        parkingSeven.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        parkingEight.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("Parking 08: ");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setText("Parking 09: ");

        parkingNine.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        parkingTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setText("Parking 10: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel1)
                                                    .addGap(56, 56, 56))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel2)
                                                    .addGap(36, 36, 36)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(56, 56, 56)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel6))
                                            .addGap(44, 44, 44)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(vehicle_parking_no, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(vehicle_token_no, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(car_radioButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(bike_radioButton))
                                        .addComponent(vehicle_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(male_radioButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(female_radioButton))
                                        .addComponent(vehicle_entrance_date, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(vehicle_entrance_time, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(parking_clear_all)
                                    .addGap(65, 65, 65)
                                    .addComponent(add_parking, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))))
                .addGap(303, 303, 303)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(113, 113, 113))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(parkingOne)
                                .addGap(29, 29, 29)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(parkingTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parkingThree, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(parkingFour, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parkingFive, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(parkingSix, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parkingSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(parkingEight, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parkingNine, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(parkingTen, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(467, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(4, 4, 4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(vehicle_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parkingOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parkingTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(car_radioButton)
                            .addComponent(bike_radioButton))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(vehicle_token_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(vehicle_parking_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(male_radioButton)
                            .addComponent(female_radioButton))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehicle_entrance_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehicle_entrance_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add_parking)
                            .addComponent(parking_clear_all)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(parkingThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parkingFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(parkingFive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parkingSix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(parkingSeven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parkingEight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(parkingNine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parkingTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("   Park Vehicle  ", jPanel1);

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));

        jLabel41.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel41.setText("Creator:");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setText("MD. Ahnaf Habib Azfar");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setText("B.Sc in CSE(2nd year), TMSS Engineering College, Bogura.");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setText("Affiliated with University of Rajshahi.");

        jLabel35.setIcon(new javax.swing.ImageIcon("C:\\Users\\azfar\\Desktop\\azfar 3.jpg")); // NOI18N
        jLabel35.setText("jLabel35");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setText("ID: 1737820106");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel33))
                .addGap(65, 65, 65)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(718, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(358, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("   About   ", jPanel4);

        datetab.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        datetab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datetabActionPerformed(evt);
            }
        });

        timetab.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel15.setBackground(new java.awt.Color(51, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Date : ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Time : ");

        jLabel17.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        jLabel17.setText("Vehicle Parking System");

        Logout.setBackground(new java.awt.Color(255, 255, 255));
        Logout.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 0, 0));
        Logout.setText("Log out");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(234, 234, 234)
                        .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datetab, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timetab, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(datetab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(timetab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)))))
                .addGap(28, 28, 28)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed

        Login Lg = new Login();
        Lg.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_LogoutActionPerformed

    private void parking_clear_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parking_clear_allActionPerformed

        vehicle_ID.setText("");
        vehicle_token_no.setText("");
        vehicle_parking_no.setText("");
        showDate();
        AnotherShowTime();
    }//GEN-LAST:event_parking_clear_allActionPerformed

    private void add_parkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_parkingActionPerformed
        // TODO add your handling code here:

        String sql = "Insert into Vehicle_Parking_Details (Vehicle_Id, Vehicle_Type, Token_No, Parking, Driver, Entrance_Date, Entrance_Time) values (?,?,?,?,?,?,?)";

        try{
            pst = conn.prepareStatement(sql);

            pst.setString(1, vehicle_ID.getText());
            pst.setString(2, Vehicle_type);
            pst.setString(3, vehicle_token_no.getText());
            pst.setString(4, vehicle_parking_no.getText());
            pst.setString(5, Vehicle_driver);
            pst.setString(6, vehicle_entrance_date.getText());
            pst.setString(7, vehicle_entrance_time.getText());

            pst.execute();

            showingParkingStatus();

            JOptionPane.showMessageDialog(null, "Added");

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

        String stringValue = vehicle_parking_no.getText();

        int  integerValue = Integer.parseInt(stringValue);

        if(integerValue == 1){
            try{
                String value1 = "Vehicle Parked";
                String sqll = "update Parking set parking_01='"+value1+"'";
                pst = conn.prepareStatement(sqll);
                pst.execute();
                ParkingCheck();

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }

        if(integerValue == 2){
            try{
                String value1 = "Vehicle Parked";
                String sqll = "update Parking set parking_02='"+value1+"'";
                pst = conn.prepareStatement(sqll);
                pst.execute();
                ParkingCheck();

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }

        if(integerValue == 3){
            try{
                String value1 = "Vehicle Parked";
                String sqll = "update Parking set parking_03='"+value1+"'";
                pst = conn.prepareStatement(sqll);
                pst.execute();
                ParkingCheck();

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }

        if(integerValue == 4){
            try{
                String value1 = "Vehicle Parked";
                String sqll = "update Parking set parking_04='"+value1+"'";
                pst = conn.prepareStatement(sqll);
                pst.execute();
                ParkingCheck();

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }

        if(integerValue == 5){
            try{
                String value1 = "Vehicle Parked";
                String sqll = "update Parking set parking_05='"+value1+"'";
                pst = conn.prepareStatement(sqll);
                pst.execute();
                ParkingCheck();

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }

        if(integerValue == 6){
            try{
                String value1 = "Vehicle Parked";
                String sqll = "update Parking set parking_06='"+value1+"'";
                pst = conn.prepareStatement(sqll);
                pst.execute();
                ParkingCheck();

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }

        if(integerValue == 7){
            try{
                String value1 = "Vehicle Parked";
                String sqll = "update Parking set parking_07='"+value1+"'";
                pst = conn.prepareStatement(sqll);
                pst.execute();
                ParkingCheck();

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }

        if(integerValue == 8){
            try{
                String value1 = "Vehicle Parked";
                String sqll = "update Parking set parking_08='"+value1+"'";
                pst = conn.prepareStatement(sqll);
                pst.execute();
                ParkingCheck();

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }

        if(integerValue == 9){
            try{
                String value1 = "Vehicle Parked";
                String sqll = "update Parking set parking_09='"+value1+"'";
                pst = conn.prepareStatement(sqll);
                pst.execute();
                ParkingCheck();

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }

        if(integerValue == 10){
            try{
                String value1 = "Vehicle Parked";
                String sqll = "update Parking set parking_10='"+value1+"'";
                pst = conn.prepareStatement(sqll);
                pst.execute();
                ParkingCheck();

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_add_parkingActionPerformed

    private void female_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_radioButtonActionPerformed
        // TODO add your handling code here:
        Vehicle_driver = "Female";
    }//GEN-LAST:event_female_radioButtonActionPerformed

    private void male_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_male_radioButtonActionPerformed
        // TODO add your handling code here:
        Vehicle_driver = "Male";
    }//GEN-LAST:event_male_radioButtonActionPerformed

    private void bike_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bike_radioButtonActionPerformed
        // TODO add your handling code here:
        Vehicle_type = "Bike";
    }//GEN-LAST:event_bike_radioButtonActionPerformed

    private void car_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_car_radioButtonActionPerformed
        // TODO add your handling code here:
        Vehicle_type = "Car";
    }//GEN-LAST:event_car_radioButtonActionPerformed

    private void vehicle_parking_noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vehicle_parking_noKeyReleased

        String stringValue = vehicle_parking_no.getText();

        int  integerValue = Integer.parseInt(stringValue);

        if(integerValue > 11){
            JOptionPane.showMessageDialog(null, "Not Possible.\nOnly (1-10) Parking Spots are available.");
            vehicle_parking_no.setText("");
        }
        if(integerValue == 0){
            JOptionPane.showMessageDialog(null, "Not Possible.\nOnly (1-10) Parking Spots are available.");
            vehicle_parking_no.setText("");
        }

        if(integerValue == 1){
            String add1 = parkingOne.getText();
            if(add1.equals("Vehicle Parked")){
                JOptionPane.showMessageDialog(null, "Vehicle is already parked on that parking.\nChoose another parking");
                vehicle_parking_no.setText("");
            }
        }

        if(integerValue == 2){
            String add1 = parkingTwo.getText();
            if(add1.equals("Vehicle Parked")){
                JOptionPane.showMessageDialog(null, "Vehicle is already parked on that parking.\nChoose another parking");
                vehicle_parking_no.setText("");
            }
        }
        if(integerValue == 3){
            String add1 = parkingThree.getText();
            if(add1.equals("Vehicle Parked")){
                JOptionPane.showMessageDialog(null, "Vehicle is already parked on that parking.\nChoose another parking");
                vehicle_parking_no.setText("");
            }
        }
        if(integerValue == 4){
            String add1 = parkingFour.getText();
            if(add1.equals("Vehicle Parked")){
                JOptionPane.showMessageDialog(null, "Vehicle is already parked on that parking.\nChoose another parking");
                vehicle_parking_no.setText("");
            }
        }
        if(integerValue == 5){
            String add1 = parkingFive.getText();
            if(add1.equals("Vehicle Parked")){
                JOptionPane.showMessageDialog(null, "Vehicle is already parked on that parking.\nChoose another parking");
                vehicle_parking_no.setText("");
            }
        }
        if(integerValue == 6){
            String add1 = parkingSix.getText();
            if(add1.equals("Vehicle Parked")){
                JOptionPane.showMessageDialog(null, "Vehicle is already parked on that parking.\nChoose another parking");
                vehicle_parking_no.setText("");
            }
        }
        if(integerValue == 7){
            String add1 = parkingSeven.getText();
            if(add1.equals("Vehicle Parked")){
                JOptionPane.showMessageDialog(null, "Vehicle is already parked on that parking.\nChoose another parking");
                vehicle_parking_no.setText("");
            }
        }
        if(integerValue == 8){
            String add1 = parkingEight.getText();
            if(add1.equals("Vehicle Parked")){
                JOptionPane.showMessageDialog(null, "Vehicle is already parked on that parking.\nChoose another parking");
                vehicle_parking_no.setText("");
            }
        }
        if(integerValue == 9){
            String add1 = parkingNine.getText();
            if(add1.equals("Vehicle Parked")){
                JOptionPane.showMessageDialog(null, "Vehicle is already parked on that parking.\nChoose another parking");
                vehicle_parking_no.setText("");
            }
        }
        if(integerValue == 10){
            String add1 = parkingTen.getText();
            if(add1.equals("Vehicle Parked")){
                JOptionPane.showMessageDialog(null, "Vehicle is already parked on that parking.\nChoose another parking");
                vehicle_parking_no.setText("");
            }
        }
    }//GEN-LAST:event_vehicle_parking_noKeyReleased

    private void search_SelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_SelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_SelectionActionPerformed

    private void show_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_allActionPerformed

        showingCheckingStatus();
    }//GEN-LAST:event_show_allActionPerformed

    private void check_In_Out_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_check_In_Out_SearchKeyReleased

        String selection = (String)search_Selection.getSelectedItem();

        String First = "Vehicle_ID";
        String Second = "Vehicle_Type";
        String Third = "Token_No";
        String Forth = "Parking";

        if(First.equals(selection)){
            try{
                String sql = "select * from Vehicle_Check_In_Out where Vehicle_Id=? ";

                pst=conn.prepareStatement(sql);
                pst.setString(1,check_In_Out_Search.getText());
                rs=pst.executeQuery();

                check_InOut_table.setModel(DbUtils.resultSetToTableModel(rs));

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else if(Second.equals(selection)){

            try{
                String sql = "select * from Vehicle_Check_In_Out where Vehicle_Type=? ";

                pst=conn.prepareStatement(sql);
                pst.setString(1,check_In_Out_Search.getText());
                rs=pst.executeQuery();

                check_InOut_table.setModel(DbUtils.resultSetToTableModel(rs));

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else if(Third.equals(selection)){

            try{
                String sql = "select * from Vehicle_Check_In_Out where Token_No=? ";

                pst=conn.prepareStatement(sql);
                pst.setString(1,check_In_Out_Search.getText());
                rs=pst.executeQuery();

                check_InOut_table.setModel(DbUtils.resultSetToTableModel(rs));

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else if(Forth.equals(selection)){

            try{
                String sql = "select * from Vehicle_Check_In_Out where Parking=? ";

                pst=conn.prepareStatement(sql);
                pst.setString(1,check_In_Out_Search.getText());
                rs=pst.executeQuery();

                check_InOut_table.setModel(DbUtils.resultSetToTableModel(rs));

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else{

        }
    }//GEN-LAST:event_check_In_Out_SearchKeyReleased

    private void clear_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_allActionPerformed

        ClearAll();
    }//GEN-LAST:event_clear_allActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int p = JOptionPane.showConfirmDialog(null, "Do you really want to Exit Parking ?", "Parking", JOptionPane.YES_NO_OPTION);

        if(p==0){

            try{

                String sql = "Insert into Vehicle_Check_In_Out (Vehicle_Id, Vehicle_Type, Token_No, Parking, Driver, Entrance_Date, Entrance_Time, Exit_Date, Exit_Time) values (?,?,?,?,?,?,?,?,?)";

                pst = conn.prepareStatement(sql);

                pst.setString(1, status_vehicle_ID.getText());
                pst.setString(2, status_vehicle_type.getText());
                pst.setString(3, status_vehicle_token_no.getText());
                pst.setString(4, status_vehicle_parking_no.getText());
                pst.setString(5, status_vehicle_driver.getText());
                pst.setString(6, status_vehicle_entrance_date.getText());
                pst.setString(7, status_vehicle_entrance_time.getText());
                pst.setString(8, datetab.getText());
                pst.setString(9, timetab.getText());

                pst.execute();

                showingCheckingStatus();

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }

            String sql = "delete from Vehicle_Parking_Details where Vehicle_Id=?";

            try{
                pst = conn.prepareStatement(sql);
                pst.setString(1, status_vehicle_ID.getText());
                pst.execute();

                JOptionPane.showMessageDialog(null, "Exit Completed");

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }

            String stringValue = status_vehicle_parking_no.getText();

            int  integerValue = Integer.parseInt(stringValue);

            if(integerValue == 1){
                try{
                    String value1 = "Free";
                    String sqll = "update Parking set parking_01='"+value1+"'";
                    pst = conn.prepareStatement(sqll);
                    pst.execute();
                    ParkingCheck();

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }

            if(integerValue == 2){
                try{
                    String value1 = "Free";
                    String sqll = "update Parking set parking_02='"+value1+"'";
                    pst = conn.prepareStatement(sqll);
                    pst.execute();
                    ParkingCheck();

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }

            if(integerValue == 3){
                try{
                    String value1 = "Free";
                    String sqll = "update Parking set parking_03='"+value1+"'";
                    pst = conn.prepareStatement(sqll);
                    pst.execute();
                    ParkingCheck();

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }

            if(integerValue == 4){
                try{
                    String value1 = "Free";
                    String sqll = "update Parking set parking_04='"+value1+"'";
                    pst = conn.prepareStatement(sqll);
                    pst.execute();
                    ParkingCheck();

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }

            if(integerValue == 5){
                try{
                    String value1 = "Free";
                    String sqll = "update Parking set parking_05='"+value1+"'";
                    pst = conn.prepareStatement(sqll);
                    pst.execute();
                    ParkingCheck();

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }

            if(integerValue == 6){
                try{
                    String value1 = "Free";
                    String sqll = "update Parking set parking_06='"+value1+"'";
                    pst = conn.prepareStatement(sqll);
                    pst.execute();
                    ParkingCheck();

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }

            if(integerValue == 7){
                try{
                    String value1 = "Free";
                    String sqll = "update Parking set parking_07='"+value1+"'";
                    pst = conn.prepareStatement(sqll);
                    pst.execute();
                    ParkingCheck();

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }

            if(integerValue == 8){
                try{
                    String value1 = "Free";
                    String sqll = "update Parking set parking_08='"+value1+"'";
                    pst = conn.prepareStatement(sqll);
                    pst.execute();
                    ParkingCheck();

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }

            if(integerValue == 9){
                try{
                    String value1 = "Free";
                    String sqll = "update Parking set parking_09='"+value1+"'";
                    pst = conn.prepareStatement(sqll);
                    pst.execute();
                    ParkingCheck();

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }

            if(integerValue == 10){
                try{
                    String value1 = "Free";
                    String sqll = "update Parking set parking_10='"+value1+"'";
                    pst = conn.prepareStatement(sqll);
                    pst.execute();
                    ParkingCheck();

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }

            showingParkingStatus();
            ClearAll();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void vehicle_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vehicle_searchKeyReleased

        try{
            String sql = "select * from Vehicle_Parking_Details where Vehicle_Id=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1,vehicle_search.getText());
            rs = pst.executeQuery();

            if(rs.next()){

                String add1 = rs.getString("Vehicle_Id");
                status_vehicle_ID.setText(add1);

                String add2 = rs.getString("Vehicle_Type");
                status_vehicle_type.setText(add2);

                String add3 = rs.getString("Token_No");
                status_vehicle_token_no.setText(add3);

                String add4 = rs.getString("Parking");
                status_vehicle_parking_no.setText(add4);

                String add5 = rs.getString("Driver");
                status_vehicle_driver.setText(add5);

                String add6 = rs.getString("Entrance_Date");
                status_vehicle_entrance_date.setText(add6);

                String add7 = rs.getString("Entrance_Time");
                status_vehicle_entrance_time.setText(add7);

            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

        /// Search By Employee ID

        try{
            String sql = "select * from Vehicle_Parking_Details where Token_No=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1,vehicle_search.getText());
            rs = pst.executeQuery();

            if(rs.next()){

                String add1 = rs.getString("Vehicle_Id");
                status_vehicle_ID.setText(add1);

                String add2 = rs.getString("Vehicle_Type");
                status_vehicle_type.setText(add2);

                String add3 = rs.getString("Token_No");
                status_vehicle_token_no.setText(add3);

                String add4 = rs.getString("Parking");
                status_vehicle_parking_no.setText(add4);

                String add5 = rs.getString("Driver");
                status_vehicle_driver.setText(add5);

                String add6 = rs.getString("Entrance_Date");
                status_vehicle_entrance_date.setText(add6);

                String add7 = rs.getString("Entrance_Time");
                status_vehicle_entrance_time.setText(add7);

            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_vehicle_searchKeyReleased

    private void parking_status_tableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_parking_status_tableKeyReleased
        // TODO add your handling code here:

        if(evt.getKeyCode()==KeyEvent.VK_DOWN || evt.getKeyCode()==KeyEvent.VK_UP){

            try{
                int row = parking_status_table.getSelectedRow();
                String Table_click = (parking_status_table.getModel().getValueAt(row,0).toString());

                String sql = "select * from Vehicle_Parking_Details where Vehicle_Id='"+Table_click+"'";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();

                if(rs.next()){
                    String add1 = rs.getString("Vehicle_Id");
                    status_vehicle_ID.setText(add1);

                    String add2 = rs.getString("Vehicle_Type");
                    status_vehicle_type.setText(add2);

                    String add3 = rs.getString("Token_No");
                    status_vehicle_token_no.setText(add3);

                    String add4 = rs.getString("Parking");
                    status_vehicle_parking_no.setText(add4);

                    String add5 = rs.getString("Driver");
                    status_vehicle_driver.setText(add5);
                }

            }catch(Exception e){

            }

        }
    }//GEN-LAST:event_parking_status_tableKeyReleased

    private void parking_status_tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_parking_status_tableKeyPressed
        // TODO add your handling code here:
        /// Not Used
    }//GEN-LAST:event_parking_status_tableKeyPressed

    private void parking_status_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parking_status_tableMouseClicked

        try{
            int row = parking_status_table.getSelectedRow();

            String Table_click = (parking_status_table.getModel().getValueAt(row,0).toString());

            String sql = "select * from Vehicle_Parking_Details where Vehicle_Id='"+Table_click+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if(rs.next()){
                String add1 = rs.getString("Vehicle_Id");
                status_vehicle_ID.setText(add1);

                String add2 = rs.getString("Vehicle_Type");
                status_vehicle_type.setText(add2);

                String add3 = rs.getString("Token_No");
                status_vehicle_token_no.setText(add3);

                String add4 = rs.getString("Parking");
                status_vehicle_parking_no.setText(add4);

                String add5 = rs.getString("Driver");
                status_vehicle_driver.setText(add5);

                String add6 = rs.getString("Entrance_Date");
                status_vehicle_entrance_date.setText(add6);

                String add7 = rs.getString("Entrance_Time");
                status_vehicle_entrance_time.setText(add7);

            }

        }catch(Exception e){

        }
    }//GEN-LAST:event_parking_status_tableMouseClicked

    private void datetabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datetabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datetabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParkingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParkingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParkingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParkingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParkingMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton add_parking;
    private javax.swing.JRadioButton bike_radioButton;
    private javax.swing.JRadioButton car_radioButton;
    private javax.swing.JTable check_InOut_table;
    private javax.swing.JTextField check_In_Out_Search;
    private javax.swing.JButton clear_all;
    private javax.swing.JTextField datetab;
    private javax.swing.JRadioButton female_radioButton;
    private javax.swing.ButtonGroup gender_Seletion_group;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton male_radioButton;
    private javax.swing.JTextField parkingEight;
    private javax.swing.JTextField parkingFive;
    private javax.swing.JTextField parkingFour;
    private javax.swing.JTextField parkingNine;
    private javax.swing.JTextField parkingOne;
    private javax.swing.JTextField parkingSeven;
    private javax.swing.JTextField parkingSix;
    private javax.swing.JTextField parkingTen;
    private javax.swing.JTextField parkingThree;
    private javax.swing.JTextField parkingTwo;
    private javax.swing.JButton parking_clear_all;
    private javax.swing.JTable parking_status_table;
    private javax.swing.JComboBox<String> search_Selection;
    private javax.swing.JButton show_all;
    private javax.swing.JTextField status_vehicle_ID;
    private javax.swing.JTextField status_vehicle_driver;
    private javax.swing.JTextField status_vehicle_entrance_date;
    private javax.swing.JTextField status_vehicle_entrance_time;
    private javax.swing.JTextField status_vehicle_parking_no;
    private javax.swing.JTextField status_vehicle_token_no;
    private javax.swing.JTextField status_vehicle_type;
    private javax.swing.JTextField timetab;
    private javax.swing.JTextField vehicle_ID;
    private javax.swing.ButtonGroup vehicle_TypeSeletion_group;
    private javax.swing.JTextField vehicle_entrance_date;
    private javax.swing.JTextField vehicle_entrance_time;
    private javax.swing.JTextField vehicle_parking_no;
    private javax.swing.JTextField vehicle_search;
    private javax.swing.JTextField vehicle_token_no;
    // End of variables declaration//GEN-END:variables
    
    private String Vehicle_type;
    private String Vehicle_driver;
}
